### ISSUE TITLE
How is it different from torch/rnn?

### ISSUE THREAD

**Issue by tastyminerals** [anoidgit/srnn#1]
1. What is the purpose of **srnn** package?
2. How is it different from both new **torch/rnn** and old **ElementResearch/rnn**?

**Comment by hfxunlp** [comment]
Actually, I embark on this project simply because that I can modify these files as I like according to my requirements. This package may become less similar with the packages you mentioned, because possibly I will have different kinds of weird requirements, for example, maybe there would be some modules which will pad several units in a batch in the first several steps with initial state and cell according to the real length of each sequence, thus It would be simpler to implement seq2seq models, with the help of [lenn](https://github.com/anoidgit/lenn) and [culenn](https://github.com/anoidgit/culenn), there will also not be a problem for attention to input a variable length batch of data to the encoder. There are no API and references available currently, which also means that I start this project only to make my development easier at least now. But thank you for your attention to this work, I'm glad if I can help you. @tastyminerals

**Comment by tastyminerals** [comment]
I got it. Thanks for the explanation.
